name: Push Event Workflow

on: push

jobs:
  unit-testing:
    runs-on: ubuntu-latest 
    
    steps:
    - name : Checkout code
      uses : actions/checkout@v2
      
    - name : Install Packages 
      run : pip install pytest
      
    - name : Install Packages 
      run : pip install -r requirements.txt
      
    - name : Run tests 
      run : pytest unit_test/run_unit_test.py
